name: Continuous Deployment pipeline for Virtual Labs PWA

on:
  push:
    branches:
      - main
      - testing

jobs:
  deploy_to_s3:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
          check-latest: true
      
      - run: |
          cd homepage
          npm install
          npm run build
          cd ../
      
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      
      - name: Sync with AWS S3
        run: aws s3 sync homepage/build/ s3://app.vlabs.ac.in --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy_to_gh_pages:
    if: github.ref == 'refs/heads/testing'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.13.0'
          check-latest: true
      
      - run: |
          cd homepage
          npm install
          npm run build
          cd ../
          git config --local user.email "admin@vlabs.ac.in"
          git config --local user.name "vleadadmin"
          git checkout --orphan gh-pages
          git reset
          git add homepage/build/* -f
          git mv homepage/build/* ./ -f
          git commit -m "https://virtual-labs.github.io/${{ github.repository }} click on the link to test your code."
      
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ORG_OWNER_GITHUB_TOKEN }}
          force: true
          branch: gh-pages
